// Code generated by mdatagen. DO NOT EDIT.

package metadata

import "go.opentelemetry.io/collector/component"

var (
	Type      = component.MustNewType("filereplay")
	ScopeName = "github.com/elastic/logsgenreceiver/logsgenreceiver/filereplayreceiver"
)

const (
	LogsStability = component.StabilityLevelDevelopment
)
