---
name: catalog-info

on:
  pull_request:
    branches:
      - main
    paths:
      - 'catalog-info.yaml'

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: elastic/oblt-actions/elastic/validate-catalog@baeee1c5aa3750bc02e694397c697c18be4c9bca # v1
